"""Single source of truth for the chassis wiring.

Edit this file and nothing else when you move a wire.
"""

# --- L298N input pairs -------------------------------------------------------
# Each motor channel is one (IN_A, IN_B) pair on a driver board.
# IN_A high / IN_B low  -> one direction.  Both low -> coast.  Both high -> brake.

DRIVER1_A = (32, 33)   # Driver 1 (right side), IN1 / IN2
DRIVER1_B = (18, 13)   # Driver 1 (right side), IN3 / IN4
DRIVER2_A = (25, 26)   # Driver 2 (left side),  IN1 / IN2
DRIVER2_B = (27, 19)   # Driver 2 (left side),  IN3 / IN4

# NOTE: IN3/IN4 were moved off GPIO12 and GPIO14 on 2026-08-29.
#   GPIO12 (MTDI) selects flash voltage at reset -- held HIGH while booting, it
#   picks 1.8V for a 3.3V flash chip and the ESP32 does not boot at all. eFuse
#   XPD_SDIO_FORCE is not burned on this board, so that pin is live. GPIO14
#   (MTMS) emits a pulse train during boot, which was the "ghost driving".
#   GPIO18 and GPIO19 replaced them: plain GPIOs, no strapping role, quiet at
#   boot. Do not move motor inputs back onto 12 or 14.

# --- Wheel map ---------------------------------------------------------------
# Which driver channel drives which corner, and whether that motor's leads are
# reversed relative to the others. Run `import selftest; selftest.run()` on the
# device to confirm these; flip `invert` for any wheel that spins backwards.

# BEGIN WHEEL MAP -- regenerated by `./teleop.sh --calibrate`, edits here are lost
WHEELS = {
    "front_left":  {"pins": DRIVER1_B, "invert": False, "trim": 1.0},
    "rear_left":   {"pins": DRIVER1_A, "invert": False, "trim": 1.0},
    "front_right": {"pins": DRIVER2_B, "invert": True, "trim": 1.0},
    "rear_right":  {"pins": DRIVER2_A, "invert": True, "trim": 1.0},
}
# END WHEEL MAP

# Order used everywhere a 4-tuple of wheel speeds is passed around.
ORDER = ("front_left", "front_right", "rear_left", "rear_right")

# Every pin this project drives, for the boot-time lockdown.
ALL_PINS = tuple(p for w in WHEELS.values() for p in w["pins"])

# --- Drive tuning ------------------------------------------------------------
PWM_FREQ = 1000        # Hz. TT motors are happy anywhere from ~500Hz to 5kHz.
MIN_DUTY = 0.35        # Below this the TT motors buzz but do not turn.

# Default speed for any command that does not name one. Rotating in place scrubs
# every mecanum roller sideways, so it needs more torque than driving straight;
# 0.8 was settled on the bench as the point where turns pivot cleanly.
DEFAULT_SPEED = 0.8
